PetShopManagement/Models/Funcionario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PetShopManagement.Models
{
    public class Funcionario
    {
        #region Propriedades
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime DataNascimento { get; set; }

        #endregion

        #region Construtores
        public Funcionario()
        {

        }
        public Funcionario(int id, string nome, string email, DateTime dataNascimento)
        {
            Id = id;
            Nome = nome;
            Email = email;
            DataNascimento = dataNascimento;
        }
        #endregion
    }
}

PetShopManagement/Controllers/FuncionariosController.cs
using Microsoft.AspNetCore.Mvc;
using PetShopManagement.Models;
using PetShopManagement.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PetShopManagement.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly FuncionarioServices _funcionarioService;

        public FuncionariosController(FuncionarioServices funcionarioService)
        {
            _funcionarioService = funcionarioService;
        }

        public IActionResult Index()
        {
            var listaFuncionarios = _funcionarioService.PesquisarTodos();
            return View(listaFuncionarios);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Funcionario funcionario)
        {
            _funcionarioService.AdicionarFuncionario(funcionario);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var funcionario = _funcionarioService.EncontrarFuncionarioPorId(id.Value);

            if (funcionario == null)
                return NotFound();

            return View(funcionario);

        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _funcionarioService.RemoverFuncionario(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id, Funcionario funcionario)
        {
            funcionario = _funcionarioService.EncontrarFuncionarioPorId(id.Value);           
            return View(funcionario);
        }

        [HttpPost]
        public IActionResult Edit(int id, Funcionario funcionario)
        {
            if (id != funcionario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _funcionarioService.EditarFuncionario(id, funcionario);               
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

PetShopManagement/Views/Funcionarios/Create.cshtml
@model Funcionario
@{
    ViewData["Title"] = "Create";
}

<h2>Cadastrar Funcionário</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
            </div>
             
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary btn-group-sm"/>
            </div>
        </form>
    </div>
</div>

PetShopManagement/Views/Funcionarios/Delete.cshtml
@model PetShopManagement.Models.Funcionario

@{
    ViewData["Title"] = "Delete";
}

<h1>Excluir</h1>
<div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>ATENÇÃO!</strong> Tem certeza que deseja excluir o registro?!
</div>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/>
        <input type="submit" value="Excluir" class="btn btn-danger" />        |     
        <a asp-action="Index">Voltar</a>
    </form>
</div>

PetShopManagement/Views/Funcionarios/Details.cshtml
@model PetShopManagement.Models.Servicos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Servicos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PetShopManagement/Views/Funcionarios/Edit.cshtml
@model PetShopManagement.Models.Funcionario

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar Serviço</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PetShopManagement/Views/Funcionarios/Index.cshtml
@model IEnumerable<Funcionario>

@{

    ViewData["Title"] = "Quadro de Funcionarios";

}

<h2>@ViewData["Title"]</h2>

<table class="table table-striped table-hover">
    <thead>
        <tr class="table-dark">
            <th>
                @Html.DisplayNameFor(Model => Model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(Model => Model.DataNascimento)
            </th>
            <th>

            </th>
        </tr>
    </thead>

    <tbody>
        @foreach(var item in Model)
            {
        <tr>
            
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento, "{0: dd-MM-yyyy}")
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar | </a>
                <a asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
            </td>
        </tr>
            }
    </tbody>
</table>

<input class="btn btn-outline-success" type="button" value="Adicionar" onclick="location.href='@Url.Action("Create", "Funcionarios")'" />